<a href="https://colab.research.google.com/github/Zian7404/Machine-Learning/blob/main/NN_CAIII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Python program to compute Hessian in PyTorch
# importing libraries
import torch
from torch.autograd.functional import hessian

Equation: x4+y4-4xy

In [ ]:
# defining a function
def func(x, y):
	return (x**4+y**4-4*x*y)

def fxx(x, y):
  return (12*x**2)

In [ ]:
input_x = torch.tensor([0.])
input_y = torch.tensor([0.])
inputs = (input_x, input_y)
print("inputs:\n", inputs)

# compute the hessian
hf = hessian(func, inputs)

# printing the above computed hessian
print("Hessian:\n", hf)

inputs:
 (tensor([0.]), tensor([0.]))
Hessian:
 ((tensor([[0.]]), tensor([[-4.]])), (tensor([[-4.]]), tensor([[0.]])))


Critical Point 1

In [ ]:
f_xx= fxx(0,0)
Df= (hf[0][0] * hf[1][1])-(hf[0][1] * hf[1][0])
Df=int(Df.item())
print(f_xx,Df)

if(Df>0):
  if(f_xx>0):
    print("Local Minima")
  else:
    print("Local Maxima")
elif(Df<0):
  print("Saddle Point")
else:
  print("Cannot be determined. Further tests required")

0 -16
Saddle Point


Critical Point 2

In [ ]:
input_x = torch.tensor([1.])
input_y = torch.tensor([1.])
inputs = (input_x, input_y)
print("inputs:\n", inputs)

# compute the hessian
hf = hessian(func, inputs)

# printing the above computed hessian
print("Hessian:\n", hf)

inputs:
 (tensor([1.]), tensor([1.]))
Hessian:
 ((tensor([[12.]]), tensor([[-4.]])), (tensor([[-4.]]), tensor([[12.]])))


In [ ]:
f_xx= fxx(1,1)
Df= (hf[0][0] * hf[1][1])-(hf[0][1] * hf[1][0])
Df=int(Df.item())
print(f_xx,Df)

if(Df>0):
  if(f_xx>0):
    print("Local Minima")
  else:
    print("Local Maxima")
elif(Df<0):
  print("Saddle Point")
else:
  print("Cannot be determined. Further tests required")

12 128
Local Minima


Critical Point 3

In [ ]:
input_x = torch.tensor([-1.])
input_y = torch.tensor([-1.])
inputs = (input_x, input_y)
print("inputs:\n", inputs)

# compute the hessian
hf = hessian(func, inputs)

# printing the above computed hessian
print("Hessian:\n", hf)

inputs:
 (tensor([-1.]), tensor([-1.]))
Hessian:
 ((tensor([[12.]]), tensor([[-4.]])), (tensor([[-4.]]), tensor([[12.]])))


In [ ]:
f_xx= fxx(-1,-1)
Df= (hf[0][0] * hf[1][1])-(hf[0][1] * hf[1][0])
Df=int(Df.item())
print(f_xx,Df)

if(Df>0):
  if(f_xx>0):
    print("Local Minima")
  else:
    print("Local Maxima")
elif(Df<0):
  print("Saddle Point")
else:
  print("Cannot be determined. Further tests required")

12 128
Local Minima
